### ISSUE TITLE
License of this repo

### ISSUE THREAD

**Issue by fewwwww** [dhruvkb/portfolio-spa#39]
This portfolio is the most genius one I see by far. 
Love it so much!
Is it possible for other developers or specifically me to use it as a template?

**Comment by dhruvkb** [comment]
Thanks for the praise. You're absolutely free to use it, I don't mind. But I would appreciate a link back, if possible.

**Comment by fewwwww** [comment]
> Thanks for the praise. You're absolutely free to use it, I don't mind. But I would appreciate a link back, if possible.

Yeah definitely will do! I was just browsing open-sources project of Creative Commons, then I find you as the contributor and your perfect portfolio. It really made my day for encountering such a well-designed portfolio.
